all:
	$(MAKE) -C "/home/ktr/Desktop/D/SC2022/Solvers/hKis/build"
kissat:
	$(MAKE) -C "/home/ktr/Desktop/D/SC2022/Solvers/hKis/build" kissat
tissat:
	$(MAKE) -C "/home/ktr/Desktop/D/SC2022/Solvers/hKis/build" tissat
clean:
	rm -f "/home/ktr/Desktop/D/SC2022/Solvers/hKis"/makefile
	-$(MAKE) -C "/home/ktr/Desktop/D/SC2022/Solvers/hKis/build" clean
	rm -rf "/home/ktr/Desktop/D/SC2022/Solvers/hKis/build"
coverage:
	$(MAKE) -C "/home/ktr/Desktop/D/SC2022/Solvers/hKis/build" coverage
indent:
	$(MAKE) -C "/home/ktr/Desktop/D/SC2022/Solvers/hKis/build" indent
test:
	$(MAKE) -C "/home/ktr/Desktop/D/SC2022/Solvers/hKis/build" test
.PHONY: all clean coverage indent kissat test tissat
