all:
	$(MAKE) -C "/home/solimul/MyComputer/C_Drive/Research/SAT/CRVR_Solvers/Kissat_extensions/Kissat-default^CRVR/build"
clean:
	rm -f "/home/solimul/MyComputer/C_Drive/Research/SAT/CRVR_Solvers/Kissat_extensions/Kissat-default^CRVR"/makefile
	-$(MAKE) -C "/home/solimul/MyComputer/C_Drive/Research/SAT/CRVR_Solvers/Kissat_extensions/Kissat-default^CRVR/build" clean
	rm -rf "/home/solimul/MyComputer/C_Drive/Research/SAT/CRVR_Solvers/Kissat_extensions/Kissat-default^CRVR/build"
coverage:
	$(MAKE) -C "/home/solimul/MyComputer/C_Drive/Research/SAT/CRVR_Solvers/Kissat_extensions/Kissat-default^CRVR/build" coverage
indent:
	$(MAKE) -C "/home/solimul/MyComputer/C_Drive/Research/SAT/CRVR_Solvers/Kissat_extensions/Kissat-default^CRVR/build" indent
test:
	$(MAKE) -C "/home/solimul/MyComputer/C_Drive/Research/SAT/CRVR_Solvers/Kissat_extensions/Kissat-default^CRVR/build" test
.PHONY: all clean coverage indent test
