all:
	$(MAKE) -C "/Users/chi_wei_chen/Desktop/2023_ICCAD_problemA/lib/sequential-solvers/kissat_pre/sources/build"
kissat:
	$(MAKE) -C "/Users/chi_wei_chen/Desktop/2023_ICCAD_problemA/lib/sequential-solvers/kissat_pre/sources/build" kissat
tissat:
	$(MAKE) -C "/Users/chi_wei_chen/Desktop/2023_ICCAD_problemA/lib/sequential-solvers/kissat_pre/sources/build" tissat
clean:
	rm -f "/Users/chi_wei_chen/Desktop/2023_ICCAD_problemA/lib/sequential-solvers/kissat_pre/sources"/makefile
	-$(MAKE) -C "/Users/chi_wei_chen/Desktop/2023_ICCAD_problemA/lib/sequential-solvers/kissat_pre/sources/build" clean
	rm -rf "/Users/chi_wei_chen/Desktop/2023_ICCAD_problemA/lib/sequential-solvers/kissat_pre/sources/build"
coverage:
	$(MAKE) -C "/Users/chi_wei_chen/Desktop/2023_ICCAD_problemA/lib/sequential-solvers/kissat_pre/sources/build" coverage
indent:
	$(MAKE) -C "/Users/chi_wei_chen/Desktop/2023_ICCAD_problemA/lib/sequential-solvers/kissat_pre/sources/build" indent
test:
	$(MAKE) -C "/Users/chi_wei_chen/Desktop/2023_ICCAD_problemA/lib/sequential-solvers/kissat_pre/sources/build" test
.PHONY: all clean coverage indent kissat test tissat
