all:
	$(MAKE) -C "/home/solimul/MyComputer/C_Drive/Research/SAT/kissat-MAB_crvr_background/build"
kissat:
	$(MAKE) -C "/home/solimul/MyComputer/C_Drive/Research/SAT/kissat-MAB_crvr_background/build" kissat
tissat:
	$(MAKE) -C "/home/solimul/MyComputer/C_Drive/Research/SAT/kissat-MAB_crvr_background/build" tissat
clean:
	rm -f "/home/solimul/MyComputer/C_Drive/Research/SAT/kissat-MAB_crvr_background"/makefile
	-$(MAKE) -C "/home/solimul/MyComputer/C_Drive/Research/SAT/kissat-MAB_crvr_background/build" clean
	rm -rf "/home/solimul/MyComputer/C_Drive/Research/SAT/kissat-MAB_crvr_background/build"
coverage:
	$(MAKE) -C "/home/solimul/MyComputer/C_Drive/Research/SAT/kissat-MAB_crvr_background/build" coverage
indent:
	$(MAKE) -C "/home/solimul/MyComputer/C_Drive/Research/SAT/kissat-MAB_crvr_background/build" indent
test:
	$(MAKE) -C "/home/solimul/MyComputer/C_Drive/Research/SAT/kissat-MAB_crvr_background/build" test
.PHONY: all clean coverage indent kissat test tissat
